# https://github.com/samarsault/texture/blob/master/_config.yml

# Name of website
title:          Florian Meinicke
tagline:        Software Developer
url:            https://fmeinicke.xyz
baseurl:        ''
paginate:       5

# Author
author:         Florian Meinicke
email:          "florian.meinicke@t-online.de"

# Theme
remote_theme: samarsault/texture

# Theme settings
texture:
  title: Florian Meinicke
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  style: black
  showPicker: false
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: About me
      url: "/aboutme"
    # - title: Resume
    #   url: "/resume"

  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github:  FMeinicke
    gitlab: FMeinicke
    stackoverflow: 12780516/fmeinicke
    linkedIn: in/florian-meinicke-6711871b5

show_excerpts: true # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - aboutme

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
